### ISSUE TITLE
Loop loading issue

### ISSUE THREAD

**Issue by soulraymusic** [elieserdejesus/JamTaba#1344]
Saved loop files do not load. This is the folder that has all the saved json files and ogg files. When I open the file from JamTaba, the tracks are empty. I will send you the example json file and ogg files.

Thanks

Ray

<img width="632" alt="Screen Shot 2020-06-26 at 5 22 50 AM" src="https://user-images.githubusercontent.com/65140559/85842089-1a5f6880-b76d-11ea-9feb-55103b2e807a.png">

**Comment by elieserdejesus** [comment]
Thanks @soulraymusic , I'm ataching your loop files here in github.

[relooploadingproblem.zip](https://github.com/elieserdejesus/JamTaba/files/4836180/relooploadingproblem.zip)

**Comment by jonjamcam** [comment]
Just wondering @elieserdejesus wasn't this issue fixed in https://github.com/elieserdejesus/JamTaba/commit/5f24092cfff46c365c5267c23229aa7eb1697250 ?

**Comment by soulraymusic** [comment]
@jonjamcam Thanks. I am using 2.1.15-beta and the attached video shows what happens when I load the loop file.
https://drive.google.com/file/d/1ptpowZjSE-82SceDhgAzvC5ovUDR4np4/view?usp=sharing

**Comment by jonjamcam** [comment]
> I am using 2.1.15-beta

Hi @soulraymusic . As stated here https://github.com/elieserdejesus/JamTaba/commit/5f24092cfff46c365c5267c23229aa7eb1697250#commitcomment-39563791 the fix was not included in the latest beta.

**Comment by elieserdejesus** [comment]
@jonjamcam , the fix is included in the beta 2 https://github.com/elieserdejesus/JamTaba/releases/tag/v2.1.15-beta2

But still crashing in Mac.

**Comment by elieserdejesus** [comment]
@soulraymusic , are you using the beta 2 (link in the previous comment) ??

**Comment by jonjamcam** [comment]
Issue https://github.com/elieserdejesus/JamTaba/issues/1295 may be related to this one. @DoublebassOO  is win10 user, so maybe beta2 could be available for Windows too IMO

**Comment by elieserdejesus** [comment]
fixed in https://github.com/elieserdejesus/JamTaba/commit/b66f33b99c429e0baddaeeeb2da553b2d6db96d7

I will release a new beta soon.

**Comment by elieserdejesus** [comment]
beta 3 released!

**Comment by soulraymusic** [comment]
@elieserdejesus the beta 3 still contains the loop loading issues. Tracks are empty.

**Comment by elieserdejesus** [comment]
sorry @soulraymusic , I messed the code versions here and not compiled the bug fixes. 

I uploaded a fixed beta 3 again. Tested here in my mac and is working fine now. Ogg loops are loaded ok and bpi and bpm bug  is fixed too.

Please let me know if is working in your side too.
https://github.com/elieserdejesus/JamTaba/releases/tag/v2.1.15-beta3

**Comment by soulraymusic** [comment]
@elieserdejesus it works now! No crash when changing bmi/bpi, loop loading ok.

**Comment by elieserdejesus** [comment]
> @elieserdejesus it works now! No crash when changing bmi/bpi, loop loading ok.

Nice news!
