### ISSUE TITLE
Instability when using jtb 2.1.0 and reaninjam reported by Bilos

### ISSUE THREAD

**Issue by jonjamcam** [elieserdejesus/JamTaba#909]
From ninbot site:

"this evening a lot of users in the lounge ninbot.com:2049 trying to chat on the active lounge.
Some crashes and obligation to reconnect jamers appeared
I noticed at the maximum users a cascade of disconnection like dominoes.
Now to know who uses jamtaba and who use reaninjam?
How many anonymous people in the lounge?
I notice that the Ninbot servers lack stability and reliability since the arrival of the new jamtaba.
Incompatibility of use between reaninjam and jamtaba?
100% reaninjam with my favorite users, there is no trouble!
why mixing the two causes crashes?"

**Comment by jonjamcam** [comment]
I'm testing 2.1.0 vst and reaninjam on win7 reaper x64. when turning camera on after some seconds inside a server I got a crash:

![image](https://user-images.githubusercontent.com/15310433/30826374-cc7aa0bc-a20c-11e7-9fef-2a138f08cc14.png)

**Comment by elieserdejesus** [comment]
@jonjamcam , I'm working in a crash report solution. The idea is detect when JamTaba was not appropriately closed in previous session. Also I'm improving the log to get more clues about the errors. I will release these changes in some days.

About your errors: nothing in the log file?

**Comment by jonjamcam** [comment]
> About your errors: nothing in the log file

I didn't check. my bad. I'll pay more attention to the log file.

**Comment by jonjamcam** [comment]
now I got a crash testing. and the log says:

`default.INFO      [22:18:21:540] JamTaba Base dir: "C:/Users/jon/AppData/Roaming/Jamtaba 2/VstPlugin" [, line 0]
default.INFO      [22:18:21:588] "Starting Jamtaba 2.1.0 Vst Plugin (x86_64) running on Windows 7 (x86_64) running in Reaper" [, line 0]
default.WARNING   [22:18:21:635] libpng warning: iCCP: known incorrect sRGB profile [, line 0]
default.WARNING   [22:18:22:467] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.WARNING   [22:18:24:918] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.WARNING   [22:18:53:532] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.WARNING   [22:19:23:547] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.WARNING   [22:19:53:563] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.WARNING   [22:20:23:571] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.WARNING   [22:20:53:585] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.WARNING   [22:21:23:615] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.WARNING   [22:21:53:615] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.WARNING   [22:22:23:630] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.WARNING   [22:22:53:644] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.WARNING   [22:23:23:659] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.WARNING   [22:23:53:675] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.WARNING   [22:24:23:690] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.WARNING   [22:24:53:706] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.CRITICAL  [22:25:21:217] invalid channel index ( "0" ), can't update the channel! [, line 0]
default.CRITICAL  [22:25:21:219] invalid channel index ( "1" ), can't update the channel! [, line 0]
default.WARNING   [22:25:23:721] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.WARNING   [22:25:53:732] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.WARNING   [22:26:23:746] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.WARNING   [22:26:53:777] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.WARNING   [22:27:23:776] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.WARNING   [22:27:53:791] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.WARNING   [22:28:23:804] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.CRITICAL  [22:28:30:885] invalid channel index ( "0" ), can't update the channel! [, line 0]
default.CRITICAL  [22:28:30:887] invalid channel index ( "1" ), can't update the channel! [, line 0]
default.DEBUG     [22:28:37:655] Setting video resolution to QSize(160, 120) [, line 0]
default.WARNING   [22:28:53:819] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.WARNING   [22:29:23:836] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.CRITICAL  [22:29:50:696] invalid channel index ( "0" ), can't update the channel! [, line 0]
default.CRITICAL  [22:29:50:698] invalid channel index ( "1" ), can't update the channel! [, line 0]
default.CRITICAL  [22:29:51:311] invalid channel index ( "0" ), can't update the channel! [, line 0]
default.CRITICAL  [22:29:51:313] invalid channel index ( "1" ), can't update the channel! [, line 0]
default.WARNING   [22:29:53:849] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.WARNING   [22:30:23:867] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.WARNING   [22:30:53:882] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.WARNING   [22:31:23:893] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.WARNING   [22:31:53:907] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.WARNING   [22:32:23:921] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
`

**Comment by elieserdejesus** [comment]
@jonjamcam , thanks for testing!

I see a lot of 
```
default.WARNING [22:29:53:849] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0] 
```

in your log file. I searched for stateChanged in the JamTaba code and found nothing related with network and **stateChanged**. 

Next step is always google 😄 

The first google result was: https://stackoverflow.com/questions/40035244/weird-warning-when-using-qnetwork

And the importante part in answer is:  It is a Bug and has been solved in Qt5.6: https://bugreports.qt.io/browse/QTIFW-822

At moment I'm compiling JamTaba with Qt 5.5.0.  

And I think @pljones have hard times trying to compile Qt 5.6 statically.

**Comment by jonjamcam** [comment]
Just crashed again. The log:

`default.INFO      [23:07:26:327] JamTaba Base dir: "C:/Users/jon/AppData/Roaming/Jamtaba 2/VstPlugin" [, line 0]
default.INFO      [23:07:26:440] "Starting Jamtaba 2.1.0 Vst Plugin (x86_64) running on Windows 7 (x86_64) running in Reaper" [, line 0]
default.WARNING   [23:07:26:487] libpng warning: iCCP: known incorrect sRGB profile [, line 0]
default.WARNING   [23:07:27:158] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.WARNING   [23:07:31:932] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.WARNING   [23:07:57:937] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.DEBUG     [23:08:04:959] Setting video resolution to QSize(160, 120) [, line 0]
default.WARNING   [23:08:27:952] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.WARNING   [23:08:57:966] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.WARNING   [23:09:27:981] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.WARNING   [23:09:57:996] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.WARNING   [23:10:28:012] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.WARNING   [23:10:58:024] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.CRITICAL  [23:11:04:757] invalid channel index ( "0" ), can't update the channel! [, line 0]
default.CRITICAL  [23:11:04:759] invalid channel index ( "1" ), can't update the channel! [, line 0]
default.WARNING   [23:11:28:039] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.DEBUG     [23:11:47:014] Setting video resolution to QSize(160, 120) [, line 0]
default.WARNING   [23:11:58:054] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.WARNING   [23:12:28:068] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.WARNING   [23:12:58:083] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.WARNING   [23:13:28:098] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.WARNING   [23:13:58:113] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.WARNING   [23:14:28:126] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.WARNING   [23:14:58:141] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.WARNING   [23:15:28:156] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.WARNING   [23:15:58:170] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.WARNING   [23:16:28:185] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.WARNING   [23:16:58:200] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.CRITICAL  [23:17:04:540] invalid channel index ( "0" ), can't update the channel! [, line 0]
default.WARNING   [23:17:28:215] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.WARNING   [23:17:58:245] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.WARNING   [23:18:28:243] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.WARNING   [23:18:58:258] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.WARNING   [23:19:28:273] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.WARNING   [23:19:58:287] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.WARNING   [23:20:28:302] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.WARNING   [23:20:58:317] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.WARNING   [23:21:28:358] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.WARNING   [23:21:58:346] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.WARNING   [23:22:28:360] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.WARNING   [23:22:58:375] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.WARNING   [23:23:28:390] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.WARNING   [23:23:58:404] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.WARNING   [23:24:28:419] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.WARNING   [23:24:58:433] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.WARNING   [23:25:28:448] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.WARNING   [23:25:58:469] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.WARNING   [23:26:28:477] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.WARNING   [23:26:58:491] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.WARNING   [23:27:28:506] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.WARNING   [23:27:58:521] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.WARNING   [23:28:28:535] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.WARNING   [23:28:58:550] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.WARNING   [23:29:28:565] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.WARNING   [23:29:58:585] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.WARNING   [23:30:28:593] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.WARNING   [23:30:58:608] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.WARNING   [23:31:28:623] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.WARNING   [23:31:58:637] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.WARNING   [23:32:28:652] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.WARNING   [23:32:58:669] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.WARNING   [23:33:28:685] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.WARNING   [23:33:58:696] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.WARNING   [23:34:28:710] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.WARNING   [23:34:58:725] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.WARNING   [23:35:28:739] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.WARNING   [23:35:58:754] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.WARNING   [23:36:28:769] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.WARNING   [23:36:58:797] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.WARNING   [23:37:28:798] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.WARNING   [23:37:58:813] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.WARNING   [23:38:28:827] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.CRITICAL  [23:38:52:869] invalid channel index ( "0" ), can't update the channel! [, line 0]
default.WARNING   [23:38:58:841] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.WARNING   [23:39:28:856] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.WARNING   [23:39:58:872] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.WARNING   [23:40:28:886] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.WARNING   [23:40:58:900] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.CRITICAL  [23:41:05:998] invalid channel index ( "0" ), can't update the channel! [, line 0]
default.CRITICAL  [23:41:22:778] invalid channel index ( "0" ), can't update the channel! [, line 0]
default.WARNING   [23:41:28:915] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.WARNING   [23:41:58:930] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.WARNING   [23:42:28:943] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.WARNING   [23:42:58:958] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.WARNING   [23:43:28:973] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.WARNING   [23:43:58:992] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.WARNING   [23:44:29:002] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.WARNING   [23:44:59:017] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.WARNING   [23:45:29:032] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.DEBUG     [23:45:55:895] Setting video resolution to QSize(160, 120) [, line 0]
default.WARNING   [23:45:59:046] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.WARNING   [23:46:29:060] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.CRITICAL  [23:46:37:678] invalid channel index ( "0" ), can't update the channel! [, line 0]
default.CRITICAL  [23:46:54:747] invalid channel index ( "0" ), can't update the channel! [, line 0]
default.CRITICAL  [23:46:54:934] invalid channel index ( "1" ), can't update the channel! [, line 0]
default.WARNING   [23:46:59:075] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.CRITICAL  [23:47:13:286] 000007FEF2F0E0DD (JamtabaVST2): (filename not available): StackWalker::ShowCallstack
 [, line 0]
default.CRITICAL  [23:47:13:485] 000007FEF2A63575 (JamtabaVST2): (filename not available): WindowsStackWalker::topLevelExceptionHandler
 [, line 0]
default.CRITICAL  [23:47:13:508] 0000000010026975 (wintab32): (filename not available): TDGetInfoExMouseBtn
 [, line 0]
default.CRITICAL  [23:47:13:524] 0000000077859450 (kernel32): (filename not available): UnhandledExceptionFilter
 [, line 0]
default.CRITICAL  [23:47:13:526] 00000000779743B8 (ntdll): (filename not available): MD5Final
 [, line 0]
default.CRITICAL  [23:47:13:528] 00000000778F85A8 (ntdll): (filename not available): _C_specific_handler
 [, line 0]
default.CRITICAL  [23:47:13:532] 0000000077909D0D (ntdll): (filename not available): RtlDecodePointer
 [, line 0]
default.CRITICAL  [23:47:13:534] 00000000778F91AF (ntdll): (filename not available): RtlUnwindEx
 [, line 0]
default.CRITICAL  [23:47:13:536] 0000000077931278 (ntdll): (filename not available): KiUserExceptionDispatcher
 [, line 0]
default.CRITICAL  [23:47:13:681] 000007FEF29FDFE4 (JamtabaVST2): (filename not available): FFMpegDemuxer::decode
 [, line 0]
default.CRITICAL  [23:47:13:699] 000007FEF29F4093 (JamtabaVST2): (filename not available): QtConcurrent::RunFunctionTask<void>::run
 [, line 0]
default.CRITICAL  [23:47:13:842] 000007FEF36B072B (JamtabaVST2): (filename not available): QThreadPoolThread::run
 [, line 0]
default.CRITICAL  [23:47:14:045] 000007FEF36915DA (JamtabaVST2): (filename not available): QThreadPrivate::start
 [, line 0]
default.CRITICAL  [23:47:14:047] 000007FEF2574F7F (MSVCR120): (filename not available): beginthreadex
 [, line 0]
default.CRITICAL  [23:47:14:049] 000007FEF2575126 (MSVCR120): (filename not available): endthreadex
 [, line 0]
default.CRITICAL  [23:47:14:051] 00000000777D652D (kernel32): (filename not available): BaseThreadInitThunk
 [, line 0]
default.CRITICAL  [23:47:14:053] 000000007790C521 (ntdll): (filename not available): RtlUserThreadStart
 [, line 0]
`

**Comment by jonjamcam** [comment]
> At moment I'm compiling JamTaba with Qt 5.5.0.

>And I think @pljones have hard times trying to compile Qt 5.6 statically.

I will give it a try tomorrow to follow the steps to compile 5.6

**Comment by elieserdejesus** [comment]
@jonjamcam , I see a important clue in your logs:
```
default.CRITICAL [23:47:13:681] 000007FEF29FDFE4 (JamtabaVST2): (filename not available): FFMpegDemuxer::decode [, line 0]
```

The crash is inside FFMpegDemuxer class, in **decode** function. As you can see we have no info about the code line (line is ZERO).  You have a **JamtabaVST2.pdb** file along side your Vst plugin? This .pdb file contain the code line infos, if this file is availble we get the exact line and file where the crash is appearing.

**Comment by jonjamcam** [comment]
> You have a JamtabaVST2.pdb file along side your Vst plugin?

yes. here's the file:: 

[JamtabaVST2.pdb.rar.txt](https://github.com/elieserdejesus/JamTaba/files/1336924/JamtabaVST2.pdb.rar.txt)

NOTE: the file was 26 MB, so I compressed it with rar and then changed the extension to .txt for uploading.

**Comment by jonjamcam** [comment]
@elieserdejesus I've had no luck compiling QT5.6 from the source. the problem is the command **nmake** is not working (it's not building as it does when using 5.5.1 sources).

![image](https://user-images.githubusercontent.com/15310433/30914611-a8bd9332-a36a-11e7-82ae-fe0b5bbb4cd5.png)

**Comment by elieserdejesus** [comment]
@jonjamcam , it's not necessary send me your pdb files. Just check if the .pdb is in the same directory of your .exe (Standalone) and dll (VST plugin). If the pdb is available in your machine the log will show the file lines.

About the Qt 5.6, I think the warning you have in your logs is not a big thing. The crashes are caused by the video decoder, the problem is in JamTaba code, not Qt.

I think we can keep using the more old Qt for while.

I will work in this video decoder bug soon.

**Comment by elieserdejesus** [comment]
@jonjamcam , can you test the new beta, please? [https://github.com/elieserdejesus/JamTaba/releases/tag/v2.1.1](https://github.com/elieserdejesus/JamTaba/releases/tag/v2.1.1)

**Comment by jonjamcam** [comment]
> can you test the new beta, please? 

Sure @elieserdejesus . It looks though that the video is making other jamtaba users crash, so my only problem while testing is not to disturb others' jam. I did test though the last crash window working ok before beta 2.1.1 release.

**Comment by jonjamcam** [comment]
just crashed using last beta 2.1.1

`default.INFO      [14:38:07:057] JamTaba Base dir: "C:/Users/jon/AppData/Roaming/JamTaba 2" [, line 0]
default.INFO      [14:38:07:220] "Starting Jamtaba 2.1.1 Standalone (x86_64) running on Windows 7 (x86_64)" [, line 0]
default.WARNING   [14:38:28:032] Can't load Qt translation for  "en.qm" [, line 0]
default.DEBUG     [14:38:28:034] Setting translation to "en" [, line 0]
default.DEBUG     [14:38:44:420] Setting video resolution to QSize(160, 120) [, line 0]`

**Comment by jonjamcam** [comment]
crash 

`default.INFO      [14:40:57:069] JamTaba Base dir: "C:/Users/jon/AppData/Roaming/JamTaba 2" [, line 0]
default.INFO      [14:40:57:230] "Starting Jamtaba 2.1.1 Standalone (x86_64) running on Windows 7 (x86_64)" [, line 0]
default.DEBUG     [14:43:14:295] Setting video resolution to QSize(160, 120) [, line 0]
default.CRITICAL  [14:43:41:122] invalid channel index ( "0" ), can't update the channel! [, line 0]
default.CRITICAL  [15:13:24:337] 000000013FE0341D (Jamtaba2): (filename not available): StackWalker::ShowCallstack
 [, line 0]
default.CRITICAL  [15:13:24:382] 000000013F9A9325 (Jamtaba2): (filename not available): WindowsStackWalker::topLevelExceptionHandler
 [, line 0]
default.CRITICAL  [15:13:24:405] 0000000010026975 (wintab32): (filename not available): TDGetInfoExMouseBtn
 [, line 0]
default.CRITICAL  [15:13:24:407] 0000000076B69450 (kernel32): (filename not available): UnhandledExceptionFilter
 [, line 0]
default.CRITICAL  [15:13:24:408] 0000000076D843B8 (ntdll): (filename not available): MD5Final
 [, line 0]
default.CRITICAL  [15:13:24:410] 0000000076D085A8 (ntdll): (filename not available): _C_specific_handler
 [, line 0]
default.CRITICAL  [15:13:24:411] 0000000076D19D0D (ntdll): (filename not available): RtlDecodePointer
 [, line 0]
default.CRITICAL  [15:13:24:412] 0000000076D091AF (ntdll): (filename not available): RtlUnwindEx
 [, line 0]
default.CRITICAL  [15:13:24:413] 0000000076D41278 (ntdll): (filename not available): KiUserExceptionDispatcher
 [, line 0]`

**Comment by elieserdejesus** [comment]
> @elieserdejesus all line 0? 

@jonjamcam , file names and line numbers are not available. In theory is just put the **JamTaba2.pdb** in same folder of executables (exe or DLL) to get these infos.

I searched for the other keyworkds in your log: TDGetInfoExMouseBtn, RtlDecodePointer, RtlUnwindEx KiUserExceptionDispatcher

A lot of results in google, many software crashing with similar stacktraces, but I have no luck to discover the bug origin.

**Comment by jonjamcam** [comment]
>  In theory is just put the JamTaba2.pdb in same folder of executables (exe or DLL) to get these infos.

Yes it's there:

![image](https://user-images.githubusercontent.com/15310433/31058490-d0d20606-a6ca-11e7-9482-9e1d2137cb44.png)

I've tested both vst and standalone and the crash happens in both. I always look at clues during jams.

**Comment by elieserdejesus** [comment]
@jonjamcam , I suspect the VST plugin pdb file need be located with the Reaper.exe folder. I think Reaper.exe is the main process and windows is trying to locate the pdb file relative to main process path.

**Comment by jonjamcam** [comment]
> I suspect the VST plugin pdb file need be located with the Reaper.exe folder. I think Reaper.exe is the main process and windows is trying to locate the pdb file relative to main process path.

I placed a copy of the file inside reaper's folder, but no crash yet. BTW I've had good results when lowering the refresh rate to 10. more stability. still testing...

**Comment by elieserdejesus** [comment]
@jonjamcam , I release a new beta: [https://github.com/elieserdejesus/JamTaba/releases/tag/v2.1.1-beta-2](https://github.com/elieserdejesus/JamTaba/releases/tag/v2.1.1-beta-2)

**Comment by jonjamcam** [comment]
first test of beta-2 in standalone working great. the other user was using old ninjam client or reaninjam. no crash. I used video, looper and ADM with no problems.

**Comment by elieserdejesus** [comment]
thanks @jonjamcam.

**Comment by jonjamcam** [comment]
2nd test with more users mostly jamtaba and video. no crashes. I think it's pretty stable now, although no long jams yet.

**Comment by elieserdejesus** [comment]
@jonjamcam , a new beta is available [https://github.com/elieserdejesus/JamTaba/releases/tag/v2.1.1-beta-3](https://github.com/elieserdejesus/JamTaba/releases/tag/v2.1.1-beta-3)

I fixed 2 very important bugs: https://github.com/elieserdejesus/JamTaba/commit/43e59da039c43f5959a0ef51f506ab3930f3aaef and https://github.com/elieserdejesus/JamTaba/commit/db06683829c02993b0d845b5bb88e6b2edf6ebda

**Comment by jonjamcam** [comment]
crash:

`default.INFO      [22:29:49:795] JamTaba Base dir: "C:/Users/jon/AppData/Roaming/Jamtaba 2/VstPlugin" [, line 0]
default.INFO      [22:29:49:841] "Starting Jamtaba 2.1.1 Vst Plugin (x86_64) running on Windows 7 (x86_64) running in Reaper" [, line 0]
default.WARNING   [22:29:49:906] libpng warning: iCCP: known incorrect sRGB profile [, line 0]
default.WARNING   [22:29:49:945] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.WARNING   [22:29:50:704] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.WARNING   [22:29:50:705] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.WARNING   [22:29:50:707] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.WARNING   [22:29:50:710] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.WARNING   [22:29:51:182] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.WARNING   [22:29:51:184] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.WARNING   [22:29:51:213] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.WARNING   [22:30:20:705] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.WARNING   [22:30:50:719] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.WARNING   [22:31:20:734] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State) [, line 0]
default.WARNING   [22:31:24:462] External WM_DESTROY received for  QWidgetWindow(0x8ba3850, name = "QWinWidgetClassWindow") , parent:  QObject(0x0) , transient parent:  QObject(0x0) [, line 0]`

**Comment by elieserdejesus** [comment]
@jonjamcam , no clues except the warning **External WM_DESTROY received for QWidgetWindow**. Are you using the metronome float window when JamTaba crashed? Or the crash appears when you closed Reaper?

**Comment by jonjamcam** [comment]
The crash appeared with no apparent cause. I was not using the float window. Btw it was only one crash the whole night and I was connected quite a bit. Many ninjamers are using beta3 now and it looks indeed very stable. I still don't have a clue either.

**Comment by elieserdejesus** [comment]
> Btw it was only one crash the whole night and I was connected quite a bit. Many ninjamers are using beta3 now and it looks indeed very stable. I still don't have a clue either.

Thanks for the good news @jonjamcam , I will release the new version today.

**Comment by elieserdejesus** [comment]
v2.1.1 released, thanks @jonjamcam  and @pljones . See you in next round 😄
